apiVersion: v1
kind: Service
metadata:
  name: ecm516-lembretes-service
spec:
  type: NodePort
  selector:
    app: lembretes
  ports: 
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata: ecm516-lembretes-clusterip-service
spec:
  selector:
    app: lembretes
  ports: 
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000